name: Publish to npm

on:
   push:
      branches:
         - main

jobs:
   publish:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
              node-version: "20"
              registry-url: "https://registry.npmjs.org"

         - name: Install dependencies
           run: npm install

         - name: Check git status
           run: git status

         - name: Commit changes
           run: |
              git config --global user.email "you@example.com"
              git config --global user.name "Your Name"
              git add .
              git commit -m "chore: update version"

         - name: Bump version and publish to npm
           env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
           run: |
              npm version patch -m "Bump version to %s"
              npm publish --access public
